"""Database connections, schemas, repositories, and migrations."""

from cctv.db.database import (
    DatabaseHealth,
    DatabaseState,
    check_database_health,
    connect_database,
    initialize_database,
)
from cctv.db.detections import (
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
    AnalysisRunPage,
    AnalysisRunRecord,
    AnalysisRunStatus,
    DetectionPage,
    DetectionRecord,
    DetectionRepository,
    TrackObservationPage,
    TrackObservationRecord,
    TrackPage,
    TrackRecord,
)
from cctv.db.display_actions import (
    DisplayActionPage,
    DisplayActionRecord,
    DisplayActionRepository,
)
from cctv.db.identities import (
    DEFAULT_MODEL_VERSION,
    MAX_EMBEDDING_DIMENSIONS,
    MAX_EMBEDDINGS_PER_BATCH,
    MIN_EMBEDDING_DIMENSIONS,
    IdentityEmbeddingInput,
    IdentityEmbeddingPage,
    IdentityEmbeddingRecord,
    IdentityEmbeddingVector,
    IdentityPage,
    IdentityRecord,
    IdentityRepository,
    normalize_embedding,
)
from cctv.db.rules import (
    RuleEventPage,
    RuleEventRecord,
    RulePage,
    RuleRecord,
    RuleRepository,
)

__all__ = [
    "DEFAULT_MODEL_VERSION",
    "DEFAULT_PAGE_SIZE",
    "MAX_EMBEDDINGS_PER_BATCH",
    "MAX_EMBEDDING_DIMENSIONS",
    "MAX_PAGE_SIZE",
    "MIN_EMBEDDING_DIMENSIONS",
    "AnalysisRunPage",
    "AnalysisRunRecord",
    "AnalysisRunStatus",
    "DatabaseHealth",
    "DatabaseState",
    "DetectionPage",
    "DetectionRecord",
    "DetectionRepository",
    "DisplayActionPage",
    "DisplayActionRecord",
    "DisplayActionRepository",
    "IdentityEmbeddingInput",
    "IdentityEmbeddingPage",
    "IdentityEmbeddingRecord",
    "IdentityEmbeddingVector",
    "IdentityPage",
    "IdentityRecord",
    "IdentityRepository",
    "RuleEventPage",
    "RuleEventRecord",
    "RulePage",
    "RuleRecord",
    "RuleRepository",
    "TrackObservationPage",
    "TrackObservationRecord",
    "TrackPage",
    "TrackRecord",
    "check_database_health",
    "connect_database",
    "initialize_database",
    "normalize_embedding",
]
