"""Registered-person face embedding extraction and enrollment."""

from cctv.identity.face import (
    SFACE_EMBEDDING_DIMENSION,
    SFACE_MODEL_NAME,
    SFACE_MODEL_VERSION,
    YUNET_MODEL_NAME,
    YUNET_MODEL_VERSION,
    DetectedFaceEmbedding,
    ExtractedFaceEmbedding,
    FaceBounds,
    FaceEmbeddingError,
    FaceEmbeddingModelMetadata,
    FaceModelLoadError,
    FacePhotoError,
    OpenCvSFaceExtractor,
)
from cctv.identity.matching import (
    FaceIdentityMatcher,
    FaceMatchDecision,
    FaceMatchingConsumer,
    FaceMatchingError,
    FaceMatchingRunSummary,
    FaceMatchObservation,
    FaceMatchRejectionReason,
    FaceMatchStatus,
    FrameFaceExtractor,
    IdentitySimilarity,
)
from cctv.identity.persistence import create_resolving_face_observation_sink
from cctv.identity.registration import (
    MAX_REGISTRATION_PHOTOS,
    MIN_REGISTRATION_PHOTOS,
    SUPPORTED_PHOTO_SUFFIXES,
    FaceEmbeddingExtractor,
    FaceRegistrationError,
    FaceRegistrationResult,
    FaceRegistrationService,
    RegisteredPhotoEmbedding,
    discover_registration_photos,
)
from cctv.identity.resolution import TrackIdentityResolver
from cctv.identity.runtime import create_sface_matching_consumer

__all__ = [
    "MAX_REGISTRATION_PHOTOS",
    "MIN_REGISTRATION_PHOTOS",
    "SFACE_EMBEDDING_DIMENSION",
    "SFACE_MODEL_NAME",
    "SFACE_MODEL_VERSION",
    "SUPPORTED_PHOTO_SUFFIXES",
    "YUNET_MODEL_NAME",
    "YUNET_MODEL_VERSION",
    "DetectedFaceEmbedding",
    "ExtractedFaceEmbedding",
    "FaceBounds",
    "FaceEmbeddingError",
    "FaceEmbeddingExtractor",
    "FaceEmbeddingModelMetadata",
    "FaceIdentityMatcher",
    "FaceMatchDecision",
    "FaceMatchObservation",
    "FaceMatchRejectionReason",
    "FaceMatchStatus",
    "FaceMatchingConsumer",
    "FaceMatchingError",
    "FaceMatchingRunSummary",
    "FaceModelLoadError",
    "FacePhotoError",
    "FaceRegistrationError",
    "FaceRegistrationResult",
    "FaceRegistrationService",
    "FrameFaceExtractor",
    "IdentitySimilarity",
    "OpenCvSFaceExtractor",
    "RegisteredPhotoEmbedding",
    "TrackIdentityResolver",
    "create_resolving_face_observation_sink",
    "create_sface_matching_consumer",
    "discover_registration_photos",
]
